name: build

on: [push, pull_request]

env:
  VERSION: 3.0
  TARGET_DIR: /build/esp32.esp32.esp32s3
  TARGET_NAME: embedded-server
  SKETCH_NAME: embedded-server.ino
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install platform
        run: |
          arduino-cli config init
          echo "board_manager:" >  /home/runner/.arduino15/arduino-cli.yaml
          echo "  additional_urls:" >>  /home/runner/.arduino15/arduino-cli.yaml
          echo "    [https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json]" >>  /home/runner/.arduino15/arduino-cli.yaml
          arduino-cli core update-index
          arduino-cli core search esp32
          arduino-cli core install esp32:esp32
      - name : Install library depencencies
        run: |
          echo "library:" >>  /home/runner/.arduino15/arduino-cli.yaml
          echo "  enable_unsafe_install: true" >>  /home/runner/.arduino15/arduino-cli.yaml
          cat /home/runner/.arduino15/arduino-cli.yaml
          for LIB in ./lib/*.zip; do echo $LIB; arduino-cli lib install --zip-path $LIB ;  done
      - name: Compile Sketch
        id: compile-sketch
        run: |
          arduino-cli compile -e --fqbn esp32:esp32:esp32s3  ./
          ls -la ./build/esp32.esp32.esp32s3


      - name: Upload .bin 
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TARGET_NAME }}${{ env.VERSION }}.bin
          path: ${{ env.TARGET_DIR }}/${{ env.SKETCH_NAME }}.bin

      - name: Upload .partitions.bin 
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TARGET_NAME }}${{ env.VERSION }}.partitions.bin
          path: ${{ env.TARGET_DIR }}/${{ env.SKETCH_NAME }}.partitions.bin

      - name: Upload .elf 
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TARGET_NAME }}${{ env.VERSION }}.elf
          path: ${{ env.TARGET_DIR }}/${{ env.SKETCH_NAME }}.elf

      - name: Upload .map 
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TARGET_NAME }}${{ env.VERSION }}.map
          path: ${{ env.TARGET_DIR }}/${{ env.SKETCH_NAME }}.map

      - name: release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TARGET_NAME }}v${{ env.VERSION }}-${{ github.run_number }}
          release_name: ${{ env.TARGET_NAME }}v${{ env.VERSION }}-${{ github.run_number }}
          draft: false
          prerelease: false